### ISSUE TITLE
Update User Update Function With New User Details

### ISSUE THREAD

**Issue by zainabch123** [boolean-uk/team-dev-server-c13#12]
- Only teachers can edit cohortId and user role.
- Add new fields to display on profile page e.g. mobile
- Update API SPEC to match updated function

**Comment by zainabch123** [comment]
PLAN:
1. Only teachers can edit cohortId and user role: In controllers → users.js, Change the updateById function so that ONLY teachers can update cohortId and user role. E.g. if if (req.user.role === 'TEACHER') { updateData.role = role}. Also delete this part of the function: (if (!cohortId) {return sendDataResponse(res, 400, {error: 'Cohort ID is required' })}). This will ensure teachers can update any part of a users profile WITHOUT needing to update the cohortId too. Also ensure 'role' is passed through to the updateById function in domain by passing it as a prop and adding it to updatedUser function.
2. Add new fields to display on profile page e.g. mobile: Change the prisma schema so that more profile/user details can be added. In particular add Username (String?) to the User model. Add Specialism (String?) and Mobile (String?) to the Profile model. Add Start Date (String?) and End Date (String?) to the Cohort Table. All these fields should be optional. Also update Data Seed (in prisma → seed.js) to add a Start Date and End Date to Cohort 1 AND could also create a cohort 2 with start and end date. Finally update the UpdateById function (in controllers → users.js) to receive these new fields from the req by updating this part of the function 'const { firstName, lastName, bio, githubUrl, cohortId, profilePicture } = req.body'.
3. Update User function in domain to also return the newly added fields e.g. mobile/specialism etc.
4. Update API SPEC to match the new response of the updated functions.

**Comment by dogezen** [comment]
Alright, go ahead with it - just ensure you have some user data existing in the DB before running the migration on prisma to check that the @unique key doesn't lockup the db
