### ISSUE TITLE
Adding createdAt to post in prisma schema

### ISSUE THREAD

**Issue by JDC-horizons** [boolean-uk/team-dev-server-c13#18]
createdAt and updatedAt fields - to add to Post entry in prisma.schema

createdAt     DateTime? @default(now())
updatedAt    DateTime? @updatedAt @default(now())

@default(now) handles future posts getting the right time added when made.
fields are also marked optional to allow for existing data that does not already have this assigned.

Ensure some data exists in the posts table when creating migration to check that prisma is happy with the new data, suggested migration name is 'add_origin_date_to_post'

**Comment by dogezen** [comment]
a) you could paste the code for PRISMA above to avoid anyone picking this up forgetting an important part
b) give example of what the @default should look like
c) mention: update `prisma.schema` and mention the migration name you recommend
