### ISSUE TITLE
Create GET endpoint for full cohort details

### ISSUE THREAD

**Issue by JDC-horizons** [boolean-uk/team-dev-server-c13#23]
Requirement: create new GET endpoint for a cohort, which returns a list of all members of that cohort. 

- Request should be made to /cohorts/{cohortId}
- endpoint logic will filter all users by the given cohort ID, then return this list of users.
- also return cohort name and start/end date (not currently implemented on database)

Responses:

- 200: users found and returned
- 400: cohort ID not valid
- 401: not authorised
- 404: no results found 

All changes will need to be updated on API spec as this endpoint does not exist currently.

Data for at least one more cohort should be added to seed to test everything works as expected.

**Comment by zainabch123** [comment]
This looks good to me although currently we only have one cohort. Will you be adding more cohorts via the data seed?

**Comment by dogezen** [comment]
Are you planning to also return the Cohort details (like name, start date, etc) on top of the members?
Also - any changes to OpenApi Spec?
