### ISSUE TITLE
Create GET endpoint for student completion statistics

### ISSUE THREAD

**Issue by JDC-horizons** [boolean-uk/team-dev-server-c13#24]
Requirement: create new GET endpoint to retrieve info for a specific user on which exercises etc are complete.

Request should be made to /users/{id}/completion

endpoint logic:
- search grades table in database for user id, then return their grades, including the id of each exercise the grade is for, and also return database info on units and modules. 
- using this info, work out which units and modules the user has completed, and combine this with which exercises they have completed into an array of completed work
- return this array to client

Responses:

200: user found, info returned
400: user ID not valid
401: not authorised
404: no user found

Example of response array:
```
[
  {
    module: 1,
    ...,
    units: [
      {unit: 1,
        ...,
        exercises: [
          {
            exercise: 1,
            ...,
            grade: {grade data}
          },
          {exercise: 2}, etc...
        ]
      },
      {unit 2:...}, etc...
    ]
  },
  {module: 2}, etc...
]
```

All changes will need to be updated on API spec as this endpoint does not exist currently.

**Comment by ezeikel** [comment]
Looks good, I would also just define what that returned array might look like @JDC-horizons

**Comment by dogezen** [comment]
I think the returned data should look more like:

```js
[
  {
    module: 1,
    ...,
    units: [
      {unit: 1,
        ...,
        exercises: [
          {
            exercise: 1,
            ...,
            grade: {grade data}
          },
          {exercise: 2}, etc...
        ]
      },
      {unit 2:...}, etc...
    ]
  },
  {module: 2}, etc...
]
```
