### ISSUE TITLE
Bugfix: Client returning 500 internal server error when retrieving posts for dashboard

### ISSUE THREAD

**Issue by JDC-horizons** [boolean-uk/team-dev-server-c13#25]
Issue: GET request to /posts/ is returning 'posts' array as undefined to client. Error occurs when opening dashboard and page tries to retrieve posts in initialisation. 

Error stack: 

```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
apiClient.js:31 
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'posts')
 at getPosts (apiClient.js:31:1)
:4000/posts:1 
        
        
 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
apiClient.js:31 
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'posts')
 at getPosts (apiClient.js:31:1)
```

Specific problem: appears to be in endpoint at #17 when selecting associated user information as part of posts array.

Potential fix: when selecting user, should then be selecting id, cohortId, role, then profile, and inside of this select firstName, lastName, bio, githubUrl and profilePicture (not profileimageUrl).

**Comment by zainabch123** [comment]
LGTM.

**Comment by dogezen** [comment]
OK - I am not 100% clear on exactly what are the conditions that cause the error:

a) is it under specific INPUT conditions that you are getting the error, or 
b) always, regardless of input?
c) have you identified with console logs to see until where the server runs code and where it gets stuck with the error?
d) what is the error stack (the full log of the server until the error?)

**Comment by dogezen** [comment]
OK - if I have understood correctly, the query being sent via prisma to fetch data is failing. Alright, let's go ahead and fix this.

Make sure to update open-api spec if the spec has changed to reflect the required INPUT conditions and expected OUTPUTS
